/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ql_xe;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.geom.RoundRectangle2D;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import dao.Contract_DAO;
import entity.Contract;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Admin
 */
public class ContractGUI extends javax.swing.JPanel implements ActionListener,MouseListener{

    /**
     * Creates new form ..
     * @throws SQLException 
     */
    public ContractGUI() throws SQLException {
        initComponents();   
        loadData();
        disableTextField();
        contractAdd.buttonAdd.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                if (e.getSource().equals(contractAdd.buttonAdd)){
                    if (contractAdd.buttonAdd.getText().equalsIgnoreCase("ĐỒNG Ý")){
                        try {
                            contractAdd.addData();
                            contractAdd.dispose();
                            updateData();
                        } catch (SQLException ex) {
                            Logger.getLogger(ContractGUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
        }
    }   
});
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        panelContractID = new javax.swing.JPanel();
        txtContractID = new RoundJTextField(30);
        labelContractID = new javax.swing.JLabel();
        panelDayContract = new javax.swing.JPanel();
        txtDayContract = new RoundJTextField(30);
        labelDayContract = new javax.swing.JLabel();
        panelMoneyToBePaid = new javax.swing.JPanel();
        txtMoneyToBePaid = new RoundJTextField(30);
        labelMoneyToBePaid = new javax.swing.JLabel();
        panelNumberOfInstallments = new javax.swing.JPanel();
        labelNumberOfInstallments = new javax.swing.JLabel();
        txtNumberOfInstallments = new RoundJTextField(30);
        panelMethod = new javax.swing.JPanel();
        labelMethod = new javax.swing.JLabel();
        comboMethod = new javax.swing.JComboBox<>();
        panelMoneyPaid = new javax.swing.JPanel();
        txtMoneyPaid = new RoundJTextField(30);
        labelMoneyPaid = new javax.swing.JLabel();
        pabelCustomerID = new javax.swing.JPanel();
        txtCustomerID = new RoundJTextField(30);
        labelCustomerID = new javax.swing.JLabel();
        panelEmployeeID = new javax.swing.JPanel();
        txtEmployeeID = new RoundJTextField(30);
        labelEmployeeID = new javax.swing.JLabel();
        panelDiscountRate = new javax.swing.JPanel();
        txtDiscountRate = new RoundJTextField(30);
        labelDiscountRate = new javax.swing.JLabel();
        buttonPay = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonSearch = new javax.swing.JButton();
        buttonAdd = new javax.swing.JButton();
        buttonDetail = new javax.swing.JButton();
        scrollTable = new javax.swing.JScrollPane();
        table = new rojeru_san.complementos.RSTableMetro();

        setPreferredSize(new java.awt.Dimension(1580, 770));

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("QUẢN LÝ HỢP ĐỒNG");
        Main.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1580, 60));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Medium", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        Header.setPreferredSize(new java.awt.Dimension(1580, 770));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContractID.setBackground(new java.awt.Color(255, 255, 255));
        panelContractID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtContractID.setBackground(new java.awt.Color(255, 255, 255));
        txtContractID.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtContractID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtContractID.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        panelContractID.add(txtContractID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 270, 30));

        labelContractID.setBackground(new java.awt.Color(255, 255, 255));
        labelContractID.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelContractID.setForeground(new java.awt.Color(0, 0, 0));
        labelContractID.setText("Mã Hợp Đồng:");
        panelContractID.add(labelContractID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 30));

        Header.add(panelContractID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 520, 40));

        panelDayContract.setBackground(new java.awt.Color(255, 255, 255));
        panelDayContract.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDayContract.setBackground(new java.awt.Color(255, 255, 255));
        txtDayContract.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtDayContract.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDayContract.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        panelDayContract.add(txtDayContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 270, 30));

        labelDayContract.setBackground(new java.awt.Color(255, 255, 255));
        labelDayContract.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelDayContract.setForeground(new java.awt.Color(0, 0, 0));
        labelDayContract.setText("Ngày Làm Hợp Đồng:");
        panelDayContract.add(labelDayContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        Header.add(panelDayContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 520, 40));

        panelMoneyToBePaid.setBackground(new java.awt.Color(255, 255, 255));
        panelMoneyToBePaid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMoneyToBePaid.setBackground(new java.awt.Color(255, 255, 255));
        txtMoneyToBePaid.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtMoneyToBePaid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMoneyToBePaid.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        panelMoneyToBePaid.add(txtMoneyToBePaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 270, 30));

        labelMoneyToBePaid.setBackground(new java.awt.Color(255, 255, 255));
        labelMoneyToBePaid.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelMoneyToBePaid.setForeground(new java.awt.Color(0, 0, 0));
        labelMoneyToBePaid.setText("Tiền Phải Thanh Toán");
        panelMoneyToBePaid.add(labelMoneyToBePaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        Header.add(panelMoneyToBePaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 520, 40));

        panelNumberOfInstallments.setBackground(new java.awt.Color(255, 255, 255));
        panelNumberOfInstallments.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNumberOfInstallments.setBackground(new java.awt.Color(255, 255, 255));
        labelNumberOfInstallments.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelNumberOfInstallments.setForeground(new java.awt.Color(0, 0, 0));
        labelNumberOfInstallments.setText("Số Lần Trả Góp:");
        panelNumberOfInstallments.add(labelNumberOfInstallments, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 30));

        txtNumberOfInstallments.setBackground(new java.awt.Color(255, 255, 255));
        txtNumberOfInstallments.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtNumberOfInstallments.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNumberOfInstallments.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        panelNumberOfInstallments.add(txtNumberOfInstallments, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 270, 30));

        Header.add(panelNumberOfInstallments, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, -1, 40));

        panelMethod.setBackground(new java.awt.Color(255, 255, 255));
        panelMethod.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMethod.setBackground(new java.awt.Color(255, 255, 255));
        labelMethod.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelMethod.setForeground(new java.awt.Color(0, 0, 0));
        labelMethod.setText("Phương Thức Thanh Toán:");
        panelMethod.add(labelMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 30));

        comboMethod.setFont(new java.awt.Font("Bahnschrift", 1, 18));
        comboMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trả Hết", "Trả Góp"}));
        panelMethod.add(comboMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 270, 30));

        Header.add(panelMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, -1, 40));

        panelMoneyPaid.setBackground(new java.awt.Color(255, 255, 255));
        panelMoneyPaid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMoneyPaid.setBackground(new java.awt.Color(255, 255, 255));
        txtMoneyPaid.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtMoneyPaid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMoneyPaid.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        panelMoneyPaid.add(txtMoneyPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 270, 30));

        labelMoneyPaid.setBackground(new java.awt.Color(255, 255, 255));
        labelMoneyPaid.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelMoneyPaid.setForeground(new java.awt.Color(0, 0, 0));
        labelMoneyPaid.setText("Tiền Đã Thanh Toán:");
        panelMoneyPaid.add(labelMoneyPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 30));

        Header.add(panelMoneyPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, 40));

        pabelCustomerID.setBackground(new java.awt.Color(255, 255, 255));
        pabelCustomerID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCustomerID.setBackground(new java.awt.Color(255, 255, 255));
        txtCustomerID.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtCustomerID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCustomerID.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        pabelCustomerID.add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 270, 30));

        labelCustomerID.setBackground(new java.awt.Color(255, 255, 255));
        labelCustomerID.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelCustomerID.setForeground(new java.awt.Color(0, 0, 0));
        labelCustomerID.setText("Mã Khách Hàng:");
        pabelCustomerID.add(labelCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        Header.add(pabelCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 520, 40));

        panelEmployeeID.setBackground(new java.awt.Color(255, 255, 255));
        panelEmployeeID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmployeeID.setBackground(new java.awt.Color(255, 255, 255));
        txtEmployeeID.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtEmployeeID.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmployeeID.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        panelEmployeeID.add(txtEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 270, 30));

        labelEmployeeID.setBackground(new java.awt.Color(255, 255, 255));
        labelEmployeeID.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelEmployeeID.setForeground(new java.awt.Color(0, 0, 0));
        labelEmployeeID.setText("Mã Nhân Viên:");
        panelEmployeeID.add(labelEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        Header.add(panelEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 520, 40));

        panelDiscountRate.setBackground(new java.awt.Color(255, 255, 255));
        panelDiscountRate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDiscountRate.setBackground(new java.awt.Color(255, 255, 255));
        txtDiscountRate.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        txtDiscountRate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDiscountRate.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        panelDiscountRate.add(txtDiscountRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 270, 30));

        labelDiscountRate.setBackground(new java.awt.Color(255, 255, 255));
        labelDiscountRate.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        labelDiscountRate.setForeground(new java.awt.Color(0, 0, 0));
        labelDiscountRate.setText("Tỉ Lệ Giảm Giá:");
        panelDiscountRate.add(labelDiscountRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 30));

        Header.add(panelDiscountRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 520, 40));

        buttonPay.setBackground(new java.awt.Color(255, 255, 255));
        buttonPay.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        buttonPay.setForeground(new java.awt.Color(0, 0, 0));
        buttonPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-history-20.png"))); // NOI18N
        buttonPay.setText("THANH TOÁN ");
        buttonPay.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonPay.setIconTextGap(15);
        buttonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPayActionPerformed(evt);
            }
        });
        Header.add(buttonPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 180, 40));

        buttonDelete.setBackground(new java.awt.Color(255, 255, 255));
        buttonDelete.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        buttonDelete.setForeground(new java.awt.Color(0, 0, 0));
        buttonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-delete-20.png"))); // NOI18N
        buttonDelete.setText("XÓA");
        buttonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonDelete.setIconTextGap(15);
        Header.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 90, 140, 40));

        buttonUpdate.setBackground(new java.awt.Color(255, 255, 255));
        buttonUpdate.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        buttonUpdate.setForeground(new java.awt.Color(0, 0, 0));
        buttonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-write-20.png"))); // NOI18N
        buttonUpdate.setText("SỬA");
        buttonUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonUpdate.setIconTextGap(15);
        Header.add(buttonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 140, 140, 40));

        buttonSearch.setBackground(new java.awt.Color(255, 255, 255));
        buttonSearch.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        buttonSearch.setForeground(new java.awt.Color(0, 0, 0));
        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-20.png"))); // NOI18N
        buttonSearch.setText("TÌM");
        buttonSearch.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonSearch.setIconTextGap(15);
        Header.add(buttonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 190, 140, 40));

        buttonAdd.setBackground(new java.awt.Color(255, 255, 255));
        buttonAdd.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(0, 0, 0));
        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-50 (2) (2).png"))); // NOI18N
        buttonAdd.setText("THÊM");
        buttonAdd.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonAdd.setIconTextGap(15);
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContract(evt);
            }
        });
        Header.add(buttonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 40, 140, 40));

        buttonDetail.setBackground(new java.awt.Color(255, 255, 255));
        buttonDetail.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 11)); // NOI18N
        buttonDetail.setForeground(new java.awt.Color(0, 0, 0));
        buttonDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-view-20.png"))); // NOI18N
        buttonDetail.setText("CHI TIẾT HỢP ĐỒNG");
        buttonDetail.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonDetail.setIconTextGap(15);
        buttonDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDetailContract(evt);
            }
        });
        buttonDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetailActionPerformed(evt);
            }
        });
        Header.add(buttonDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 270, 40));

        Main.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1560, 251));

        scrollTable.setBackground(new java.awt.Color(255, 255, 255));
        scrollTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setBorder(new javax.swing.border.MatteBorder(null));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"ád", "ád", "ád", "ád"},
                {"áđá", "ád", "ád", "ád"},
                {"áđá", "d", "ád", "áđá"},
                {"áđá", "áđá", "áđá", "ád"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        table.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        table.setColorBordeHead(new java.awt.Color(255, 255, 255));
        table.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        table.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        table.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        table.setColorSelBackgound(new java.awt.Color(51, 51, 51));
        table.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        table.setFuenteFilas(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        table.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table.setGridColor(new java.awt.Color(0, 0, 0));
        table.setRowHeight(25);
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table.setShowGrid(false);
        table.setShowVerticalLines(true);
        table.setSurrendersFocusOnKeystroke(true);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickTable(evt);
            }
        });
        scrollTable.setViewportView(table);
        model = new DefaultTableModel(new String[] {"Mã Hợp Đồng", "Khách Hàng", "Nhân Viên", "Ngày Hợp Đồng", "Thanh Toán", "Đã Trả", "Số Lần Trả"},0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        table.setModel(model);

        Main.add(scrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 1560, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 1584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPayActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
		if (evt.getSource().equals(buttonAdd)){
                    contractAdd.setVisible(true);
                }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDetailActionPerformed

    private void buttonDetailContract(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDetailContract
        // TODO add your handling code here:
        contractAdd.setVisible(true);
        
    }//GEN-LAST:event_buttonDetailContract

    private void addContract(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContract
        // TODO add your handling code here:
        if (evt.getSource().equals(buttonAdd)){
                    contractAdd.setVisible(true);
                }
    }//GEN-LAST:event_addContract

    private void clickTable(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickTable
                if (evt.getSource().equals(table)){
                    if (table.getSelectedRow()!=-1){
                            try {
                            Contract temp = contractDao.getContract(Integer.valueOf(table.getValueAt(table.getSelectedRow(), 0).toString()));
                            txtContractID.setText(String.valueOf(temp.getContractID()));
                            txtCustomerID.setText(String.valueOf(temp.getCustomerID()));
                            txtDayContract.setText(String.valueOf(temp.getContractDate()));
                            txtDiscountRate.setText(String.valueOf(temp.getDiscount()));
                            txtEmployeeID.setText(String.valueOf(temp.getStaffID()));
                            txtMoneyPaid.setText(String.format("%.3f", temp.getMoneypaied()));
                            txtMoneyToBePaid.setText(String.format("%.3f",temp.getMoneyPay()));
                            txtNumberOfInstallments.setText(String.valueOf(temp.getTimePay()));
                        } catch (SQLException ex) {
                            Logger.getLogger(ContractGUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
        }
 
    }//GEN-LAST:event_clickTable


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Main;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDetail;
    protected javax.swing.JButton buttonPay;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox<String> comboMethod;
    private javax.swing.JLabel labelContractID;
    private javax.swing.JLabel labelCustomerID;
    private javax.swing.JLabel labelDayContract;
    private javax.swing.JLabel labelDiscountRate;
    private javax.swing.JLabel labelEmployeeID;
    private javax.swing.JLabel labelMethod;
    private javax.swing.JLabel labelMoneyPaid;
    private javax.swing.JLabel labelMoneyToBePaid;
    private javax.swing.JLabel labelNumberOfInstallments;
    private javax.swing.JPanel pabelCustomerID;
    private javax.swing.JPanel panelContractID;
    private javax.swing.JPanel panelDayContract;
    private javax.swing.JPanel panelDiscountRate;
    private javax.swing.JPanel panelEmployeeID;
    private javax.swing.JPanel panelMethod;
    private javax.swing.JPanel panelMoneyPaid;
    private javax.swing.JPanel panelMoneyToBePaid;
    private javax.swing.JPanel panelNumberOfInstallments;
    private javax.swing.JScrollPane scrollTable;
    private rojeru_san.complementos.RSTableMetro table;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtContractID;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextField txtDayContract;
    private javax.swing.JTextField txtDiscountRate;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtMoneyPaid;
    private javax.swing.JTextField txtMoneyToBePaid;
    private javax.swing.JTextField txtNumberOfInstallments;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel model;
    private PaymentGUI payment = new PaymentGUI();
    private GUI gui;
    private dao.Contract_DAO contractDao;
    private ArrayList<Contract> data;
    private ContractAdd contractAdd = new ContractAdd();
    
    
    public class RoundJTextField extends JTextField {
    private Shape shape;
    public RoundJTextField(int size) {
        super(size);
        setOpaque(false); // As suggested by @AVD in comment.
    }
    protected void paintComponent(Graphics g) {
         g.setColor(getBackground());
         g.fillRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
         super.paintComponent(g);
    }
    protected void paintBorder(Graphics g) {
         g.setColor(Color.BLACK);
         g.drawRoundRect(0, 0, getWidth()-1, getHeight()-1, 15, 15);
    }
    public boolean contains(int x, int y) {
         if (shape == null || !shape.getBounds().equals(getBounds())) {
             shape = new RoundRectangle2D.Float(0, 0, getWidth()-1, getHeight()-1, 15, 15);
         }
         return shape.contains(x, y);
    }
}
    
    public  void loadData() throws SQLException {
    	contractDao = new Contract_DAO();
    	data = contractDao.getAllContract();
    	for(Contract tmp:data) {
    		String[] tmpRow = {Integer.toString(tmp.getContractID()),
    				Integer.toString(tmp.getCustomerID()),
    				Integer.toString(tmp.getStaffID()),
    				tmp.getContractDate().format(DateTimeFormatter.ofPattern("d-M-yyyy")),
    				String.format("%.3f",tmp.getMoneyPay()),
    				String.format("%.3f",tmp.getMoneypaied() ),
    				Integer.toString(tmp.getTimePay())};
    		model.addRow(tmpRow);
    				
    			
    	}
    }
    
    public void setNullTextField() {
		txtContractID.setText("");
		txtContractID.requestFocus();
		txtDayContract.setText("");
		txtMoneyToBePaid.setText("");
		txtNumberOfInstallments.setText("");
		txtMoneyPaid.setText("");
		txtCustomerID.setText("");
		txtEmployeeID.setText("");
		txtDiscountRate.setText("");
		comboMethod.setSelectedIndex(0);
	}
	
	public void disableTextField() {
		txtContractID.setEnabled(false);
		txtDayContract.setEnabled(false);
		txtMoneyToBePaid.setEnabled(false);
		txtNumberOfInstallments.setEnabled(false);
		txtMoneyPaid.setEnabled(false);
		txtCustomerID.setEnabled(false);
		txtEmployeeID.setEnabled(false);
		txtDiscountRate.setEnabled(false);
		comboMethod.setEnabled(false);
		txtContractID.setBackground(Color.getHSBColor(0f, 0f,0.79f));
		txtDayContract.setBackground(Color.getHSBColor(0f, 0f,0.79f));
		txtMoneyToBePaid.setBackground(Color.getHSBColor(0f, 0f,0.79f));
		txtNumberOfInstallments.setBackground(Color.getHSBColor(0f, 0f,0.79f));
		txtMoneyPaid.setBackground(Color.getHSBColor(0f, 0f,0.79f));
		txtCustomerID.setBackground(Color.getHSBColor(0f, 0f,0.79f));
		txtEmployeeID.setBackground(Color.getHSBColor(0f, 0f,0.79f));
		txtDiscountRate.setBackground(Color.getHSBColor(0f, 0f,0.79f));
		comboMethod.setBackground(Color.getHSBColor(0f, 0f,0.79f));
	}
	
	public void enableTextField() {
		txtContractID.setEnabled(true);
		txtDayContract.setEnabled(true);
		txtMoneyToBePaid.setEnabled(true);
		txtNumberOfInstallments.setEnabled(true);
		txtMoneyPaid.setEnabled(true);
		txtCustomerID.setEnabled(true);
		txtEmployeeID.setEnabled(true);
		txtDiscountRate.setEnabled(true);
		comboMethod.setEnabled(true);
		// set color 
		txtContractID.setBackground(Color.WHITE);
		txtDayContract.setBackground(Color.WHITE);
		txtMoneyToBePaid.setBackground(Color.WHITE);
		txtNumberOfInstallments.setBackground(Color.WHITE);
		txtMoneyPaid.setBackground(Color.WHITE);
		txtCustomerID.setBackground(Color.WHITE);
		txtEmployeeID.setBackground(Color.WHITE);
		txtDiscountRate.setBackground(Color.WHITE);
		comboMethod.setBackground(Color.WHITE);
		
	}
	
	public void updateData() throws SQLException {
		model.setRowCount(0);
		contractDao = new Contract_DAO();
		ArrayList<Contract> list = new ArrayList<>();
		list = contractDao.getAllContract();
		for(Contract tmp:list) {
			String[] tmpRow = {Integer.toString(tmp.getContractID()),
    				Integer.toString(tmp.getCustomerID()),
    				Integer.toString(tmp.getStaffID()),
    				tmp.getContractDate().format(DateTimeFormatter.ofPattern("d-M-yyyy")),
    				String.format("%.3f",tmp.getMoneyPay()),
    				String.format("%.3f",tmp.getMoneypaied() ),
    				Integer.toString(tmp.getTimePay())};
    		model.addRow(tmpRow);
		}
	}
        
	
	@Override
	public void actionPerformed(ActionEvent e) {

	}

	@Override
	public void mouseClicked(MouseEvent e) {
		if(e.getSource().equals(table)) {
			int index = table.getSelectedRow();
			txtContractID.setText((String) model.getValueAt(index,0));
			txtCustomerID.setText((String) model.getValueAt(index,1));
			txtDayContract.setText((String) model.getValueAt(index,3));
			txtEmployeeID.setText((String) model.getValueAt(index,2));
			txtMoneyPaid.setText((String) model.getValueAt(index,5));
			txtMoneyToBePaid.setText((String) model.getValueAt(index,4));
			txtNumberOfInstallments.setText((String) model.getValueAt(index,6));
		}
		
	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub
		
	}
	

}
