/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ql_xe;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author dell
 */
public class GUI extends javax.swing.JFrame implements ActionListener{
    /**
     * Creates new form GUI
     */
    public GUI() throws SQLException {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2-getHeight()/2);
        Contract.buttonPay.addActionListener(this);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenuMain = new javax.swing.JPanel();
        pMenu = new javax.swing.JPanel();
        Panel_Exit = new javax.swing.JPanel();
        Label_Exit = new javax.swing.JLabel();
        panelHomePage = new javax.swing.JPanel();
        Label_HomePage = new javax.swing.JLabel();
        panelVehicleManagement = new javax.swing.JPanel();
        Label_VehicleManagement = new javax.swing.JLabel();
        panelCustomer = new javax.swing.JPanel();
        Label_Customer = new javax.swing.JLabel();
        panelBill = new javax.swing.JPanel();
        Label_Bill = new javax.swing.JLabel();
        panelPay = new javax.swing.JPanel();
        Label_Pay = new javax.swing.JLabel();
        panelWarranty = new javax.swing.JPanel();
        Label_Warranty = new javax.swing.JLabel();
        panelEmployee = new javax.swing.JPanel();
        Label_Employee = new javax.swing.JLabel();
        panelHistory = new javax.swing.JPanel();
        Label_History = new javax.swing.JLabel();
        Panel_LogOut = new javax.swing.JPanel();
        Label_LogOut = new javax.swing.JLabel();
        Panel_Logo = new javax.swing.JPanel();
        Label_Logo = new javax.swing.JLabel();
        panelStatistical = new javax.swing.JPanel();
        Label_Statistical = new javax.swing.JLabel();
        pHomePage = new javax.swing.JPanel();
        Panel_ButtonMenu = new javax.swing.JPanel();
        Label_ButtonMenu = new javax.swing.JLabel();
        NameSystemTxt = new javax.swing.JLabel();
        NameSystem = new javax.swing.JPanel();
        NameSystemLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);
        setSize(
            1080, 900);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pMenuMain.setBackground(new java.awt.Color(255, 255, 255));
        pMenuMain.setForeground(new java.awt.Color(255, 255, 255));
        pMenuMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pMenu.setBackground(new java.awt.Color(255, 255, 255));
        pMenu.setPreferredSize(new java.awt.Dimension(222, 1140));
        pMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });
        pMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Exit.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });

        Label_Exit.setBackground(new java.awt.Color(255, 255, 255));
        Label_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close_icon.png"))); // NOI18N

        javax.swing.GroupLayout Panel_ExitLayout = new javax.swing.GroupLayout(Panel_Exit);
        Panel_Exit.setLayout(Panel_ExitLayout);
        Panel_ExitLayout.setHorizontalGroup(
            Panel_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        Panel_ExitLayout.setVerticalGroup(
            Panel_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ExitLayout.createSequentialGroup()
                .addComponent(Label_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pMenu.add(Panel_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 0, 40, 40));

        panelHomePage.setBackground(new Color(242,242,242));
        panelHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Click_HomePage(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });

        Label_HomePage.setBackground(new java.awt.Color(0, 0, 0));
        Label_HomePage.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_HomePage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_HomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        Label_HomePage.setText("Trang chủ");

        javax.swing.GroupLayout panelHomePageLayout = new javax.swing.GroupLayout(panelHomePage);
        panelHomePage.setLayout(panelHomePageLayout);
        panelHomePageLayout.setHorizontalGroup(
            panelHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_HomePage, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHomePageLayout.setVerticalGroup(
            panelHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomePageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_HomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pMenu.add(panelHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 60));

        panelVehicleManagement.setBackground(new Color(242,242,242));
        panelVehicleManagement.setPreferredSize(new java.awt.Dimension(220, 62));
        panelVehicleManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Click_MotobikePanel(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });

        Label_VehicleManagement.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_VehicleManagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_VehicleManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/xe.png"))); // NOI18N
        Label_VehicleManagement.setText("Xe");

        javax.swing.GroupLayout panelVehicleManagementLayout = new javax.swing.GroupLayout(panelVehicleManagement);
        panelVehicleManagement.setLayout(panelVehicleManagementLayout);
        panelVehicleManagementLayout.setHorizontalGroup(
            panelVehicleManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVehicleManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_VehicleManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelVehicleManagementLayout.setVerticalGroup(
            panelVehicleManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVehicleManagementLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Label_VehicleManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(700, 700, 700))
        );

        pMenu.add(panelVehicleManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 220, 60));

        panelCustomer.setBackground(new Color(242,242,242));
        panelCustomer.setPreferredSize(new java.awt.Dimension(220, 62));
        panelCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Click_CustomerPanel(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });

        Label_Customer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_Customer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-customer-20.png"))); // NOI18N
        Label_Customer.setText("Khách Hàng");

        javax.swing.GroupLayout panelCustomerLayout = new javax.swing.GroupLayout(panelCustomer);
        panelCustomer.setLayout(panelCustomerLayout);
        panelCustomerLayout.setHorizontalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Customer, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCustomerLayout.setVerticalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Customer, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pMenu.add(panelCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 220, 60));

        panelBill.setBackground(new Color(242,242,242));
        panelBill.setPreferredSize(new java.awt.Dimension(220, 62));
        panelBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Click_Bill(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });

        Label_Bill.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_Bill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill.png"))); // NOI18N
        Label_Bill.setText("Hợp Đồng");

        javax.swing.GroupLayout panelBillLayout = new javax.swing.GroupLayout(panelBill);
        panelBill.setLayout(panelBillLayout);
        panelBillLayout.setHorizontalGroup(
            panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Bill, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBillLayout.setVerticalGroup(
            panelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Bill, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pMenu.add(panelBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 220, 60));

        panelPay.setBackground(new Color(242,242,242));
        panelPay.setPreferredSize(new java.awt.Dimension(220, 62));
        panelPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Click_Payment(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });

        Label_Pay.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_Pay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pay.png"))); // NOI18N
        Label_Pay.setText("Phiếu Thu");

        javax.swing.GroupLayout panelPayLayout = new javax.swing.GroupLayout(panelPay);
        panelPay.setLayout(panelPayLayout);
        panelPayLayout.setHorizontalGroup(
            panelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Pay, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPayLayout.setVerticalGroup(
            panelPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Pay, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pMenu.add(panelPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 220, 60));

        panelWarranty.setBackground(new Color(242,242,242));
        panelWarranty.setPreferredSize(new java.awt.Dimension(220, 62));
        panelWarranty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Click_Warranty(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });

        Label_Warranty.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_Warranty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Warranty.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-guarantee-20.png"))); // NOI18N
        Label_Warranty.setText("Bảo Hành");

        javax.swing.GroupLayout panelWarrantyLayout = new javax.swing.GroupLayout(panelWarranty);
        panelWarranty.setLayout(panelWarrantyLayout);
        panelWarrantyLayout.setHorizontalGroup(
            panelWarrantyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarrantyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Warranty, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelWarrantyLayout.setVerticalGroup(
            panelWarrantyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWarrantyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Warranty, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pMenu.add(panelWarranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 220, 60));

        panelEmployee.setBackground(new Color(242,242,242));
        panelEmployee.setPreferredSize(new java.awt.Dimension(220, 62));
        panelEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Click_Information(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });

        Label_Employee.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_Employee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-employee-30.png"))); // NOI18N
        Label_Employee.setText("Nhân Viên");

        javax.swing.GroupLayout panelEmployeeLayout = new javax.swing.GroupLayout(panelEmployee);
        panelEmployee.setLayout(panelEmployeeLayout);
        panelEmployeeLayout.setHorizontalGroup(
            panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Employee, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEmployeeLayout.setVerticalGroup(
            panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Employee, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pMenu.add(panelEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 220, 60));

        panelHistory.setBackground(new Color(242,242,242));
        panelHistory.setPreferredSize(new java.awt.Dimension(220, 62));
        panelHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Click_History(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });

        Label_History.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_History.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_History.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-history-20.png"))); // NOI18N
        Label_History.setText("Lịch Sử");
        Label_History.setFocusCycleRoot(true);
        Label_History.setPreferredSize(new java.awt.Dimension(1, 22));
        Label_History.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelHistoryLayout = new javax.swing.GroupLayout(panelHistory);
        panelHistory.setLayout(panelHistoryLayout);
        panelHistoryLayout.setHorizontalGroup(
            panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_History, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHistoryLayout.setVerticalGroup(
            panelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_History, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pMenu.add(panelHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 220, 60));

        Panel_LogOut.setBackground(new Color(242,242,242));
        Panel_LogOut.setPreferredSize(new java.awt.Dimension(220, 62));
        Panel_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Click_Exit(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });

        Label_LogOut.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_LogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/out.png"))); // NOI18N
        Label_LogOut.setText("Đăng xuất");
        Label_LogOut.setFocusCycleRoot(true);
        Label_LogOut.setFocusTraversalPolicy(null);
        Label_LogOut.setPreferredSize(new java.awt.Dimension(1, 22));
        Label_LogOut.setRequestFocusEnabled(false);

        javax.swing.GroupLayout Panel_LogOutLayout = new javax.swing.GroupLayout(Panel_LogOut);
        Panel_LogOut.setLayout(Panel_LogOutLayout);
        Panel_LogOutLayout.setHorizontalGroup(
            Panel_LogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_LogOutLayout.setVerticalGroup(
            Panel_LogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_LogOut, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pMenu.add(Panel_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 780, 220, 60));

        Panel_Logo.setBackground(new java.awt.Color(255, 255, 255));

        Label_Logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_menu.png"))); // NOI18N

        javax.swing.GroupLayout Panel_LogoLayout = new javax.swing.GroupLayout(Panel_Logo);
        Panel_Logo.setLayout(Panel_LogoLayout);
        Panel_LogoLayout.setHorizontalGroup(
            Panel_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Logo)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        Panel_LogoLayout.setVerticalGroup(
            Panel_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LogoLayout.createSequentialGroup()
                .addComponent(Label_Logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pMenu.add(Panel_Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 441, 140));

        panelStatistical.setBackground(new Color(242,242,242));
        panelStatistical.setPreferredSize(new java.awt.Dimension(220, 62));
        panelStatistical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Click_Status(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });

        Label_Statistical.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Label_Statistical.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Statistical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-chart-20.png"))); // NOI18N
        Label_Statistical.setText("Thống Kê");
        Label_Statistical.setFocusCycleRoot(true);
        Label_Statistical.setPreferredSize(new java.awt.Dimension(1, 22));
        Label_Statistical.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelStatisticalLayout = new javax.swing.GroupLayout(panelStatistical);
        panelStatistical.setLayout(panelStatisticalLayout);
        panelStatisticalLayout.setHorizontalGroup(
            panelStatisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatisticalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Statistical, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelStatisticalLayout.setVerticalGroup(
            panelStatisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStatisticalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Statistical, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        pMenu.add(panelStatistical, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 220, 60));

        pMenuMain.add(pMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 0, 1950));

        pHomePage.setBackground(new java.awt.Color(255, 255, 255));
        pHomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pHomePage.setRequestFocusEnabled(false);
        pHomePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_ButtonMenu.setBackground(new java.awt.Color(0, 0, 0));
        Panel_ButtonMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_EnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Enter_MenuChangeColor(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Exit_MenuChangeColor(evt);
            }
        });
        Panel_ButtonMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_ButtonMenu.setBackground(new java.awt.Color(255, 255, 255));
        Label_ButtonMenu.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Label_ButtonMenu.setForeground(new java.awt.Color(255, 255, 255));
        Label_ButtonMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ButtonMenu.setText("≡");
        Panel_ButtonMenu.add(Label_ButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 70));
        Label_ButtonMenu.getAccessibleContext().setAccessibleParent(panelCustomer);

        pHomePage.add(Panel_ButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 80));

        NameSystemTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameSystemTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/System.jpg"))); // NOI18N
        pHomePage.add(NameSystemTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 80));

        pMenuMain.add(pHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        NameSystem.setBackground(new java.awt.Color(0, 0, 0));
        NameSystem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameSystemLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modelo-de-banner-de-corrida-de-velocidade-de-moto_23-2148576035.png"))); // NOI18N
        NameSystem.add(NameSystemLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 770));

        pMenuMain.add(NameSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1580, 740));

        getContentPane().add(pMenuMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit_MenuChangeColor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit_MenuChangeColor
        // TODO add your handling code here:
        JPanel temp = (JPanel) evt.getSource();
        temp.setBackground(new Color(244,244,244));
        if (temp.equals(Panel_Exit))
            temp.setBackground(new Color(255,255,255));
        if (temp.equals(Panel_ButtonMenu))
            temp.setBackground(new Color(0,0,0));
        if (temp.equals(pMenu)){
            temp.setBackground(new Color(255,255,255));
                    this.requestFocus();
        }
        
    }//GEN-LAST:event_Exit_MenuChangeColor

    private void Enter_MenuChangeColor(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Enter_MenuChangeColor
        // TODO add your handling code here:
        this.requestFocus();
        JPanel temp = (JPanel) evt.getSource();
        temp.setBackground(Color.GRAY);
        if(temp.equals(pMenu)){
            temp.setBackground(new Color(255,255,255));
        }
    }//GEN-LAST:event_Enter_MenuChangeColor

    private void Panel_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ExitMouseClicked
        closeMenuBar();
        setVisible(false);
        setVisible(true);
        Panel_ButtonMenu.setVisible(true);
    }//GEN-LAST:event_Panel_ExitMouseClicked

    private void Panel_EnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_EnterMouseClicked
         openMenuBar();
         Panel_ButtonMenu.setVisible(false);

    }//GEN-LAST:event_Panel_EnterMouseClicked

    private void Click_MotobikePanel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click_MotobikePanel
        // TODO add your handling code here:
        closeMenuBar();
        pMenuMain.remove(2);
        Panel_ButtonMenu.setVisible(true);
        pMenuMain.add(Motobike,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1580, 740));
    }//GEN-LAST:event_Click_MotobikePanel

    private void Click_HomePage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click_HomePage
        closeMenuBar();
        setVisible(false);
        setVisible(true);
        pMenuMain.remove(2);
        Panel_ButtonMenu.setVisible(true);
        pMenuMain.add(HomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1580, 740));
    }//GEN-LAST:event_Click_HomePage

    private void Click_CustomerPanel(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click_CustomerPanel
        // TODO add your handling code here:
        closeMenuBar();
        pMenuMain.remove(2);
        Panel_ButtonMenu.setVisible(true);
        pMenuMain.add(Customer,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1580, 740));
    }//GEN-LAST:event_Click_CustomerPanel

    private void Click_Bill(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click_Bill
        // TODO add your handling code here:
        closeMenuBar();
        pMenuMain.remove(2);
        Panel_ButtonMenu.setVisible(true);
        pMenuMain.add(Contract,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1580, 740));
    }//GEN-LAST:event_Click_Bill

    private void Click_Payment(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click_Payment
         // TODO add your handling code here:
        closeMenuBar();
        pMenuMain.remove(2);
        Panel_ButtonMenu.setVisible(true);
        pMenuMain.add(Payment,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1580, 740));
    }//GEN-LAST:event_Click_Payment

    private void Click_Warranty(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click_Warranty
        // TODO add your handling code here:
        closeMenuBar();
        pMenuMain.remove(2);
        Panel_ButtonMenu.setVisible(true);
        pMenuMain.add(Warranty, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1580, 740));
    }//GEN-LAST:event_Click_Warranty

    private void Click_Information(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click_Information
        // TODO add your handling code here:
        closeMenuBar();
        pMenuMain.remove(2);
        Panel_ButtonMenu.setVisible(true);
        pMenuMain.add(Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1580, 740));
    }//GEN-LAST:event_Click_Information

    private void Click_Exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click_Exit
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_Click_Exit

    private void Click_History(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click_History
        // TODO add your handling code here:
        closeMenuBar();
        pMenuMain.remove(2);
        Panel_ButtonMenu.setVisible(true);
        pMenuMain.add(History, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1580, 740));
        History.loadData();
    }//GEN-LAST:event_Click_History

    private void Click_Status(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click_Status
        // TODO add your handling code here:
        closeMenuBar();
        pMenuMain.remove(2);
        Panel_ButtonMenu.setVisible(true);
        pMenuMain.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1580, 740));
    }//GEN-LAST:event_Click_Status

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Bill;
    private javax.swing.JLabel Label_ButtonMenu;
    private javax.swing.JLabel Label_Customer;
    private javax.swing.JLabel Label_Employee;
    private javax.swing.JLabel Label_Exit;
    private javax.swing.JLabel Label_History;
    private javax.swing.JLabel Label_HomePage;
    private javax.swing.JLabel Label_LogOut;
    private javax.swing.JLabel Label_Logo;
    private javax.swing.JLabel Label_Pay;
    private javax.swing.JLabel Label_Statistical;
    private javax.swing.JLabel Label_VehicleManagement;
    private javax.swing.JLabel Label_Warranty;
    private javax.swing.JPanel NameSystem;
    private javax.swing.JLabel NameSystemLabel;
    private javax.swing.JLabel NameSystemTxt;
    private javax.swing.JPanel Panel_ButtonMenu;
    private javax.swing.JPanel Panel_Exit;
    private javax.swing.JPanel Panel_LogOut;
    private javax.swing.JPanel Panel_Logo;
    private javax.swing.JPanel pHomePage;
    private javax.swing.JPanel pMenu;
    private javax.swing.JPanel pMenuMain;
    private javax.swing.JPanel panelBill;
    private javax.swing.JPanel panelCustomer;
    private javax.swing.JPanel panelEmployee;
    private javax.swing.JPanel panelHistory;
    private javax.swing.JPanel panelHomePage;
    private javax.swing.JPanel panelPay;
    private javax.swing.JPanel panelStatistical;
    private javax.swing.JPanel panelVehicleManagement;
    private javax.swing.JPanel panelWarranty;
    // End of variables declaration//GEN-END:variables
    private MotobikeGUI Motobike = new MotobikeGUI();
    private CustomerGUI Customer = new CustomerGUI();
    private HomePageGUI HomePage = new HomePageGUI();
    private ContractGUI Contract = new ContractGUI();
    private PaymentGUI  Payment = new PaymentGUI();
    private WarrantyGUI Warranty = new WarrantyGUI();
    private EmployeeGUI Employee = new EmployeeGUI();
    private HistoryGUI  History = new HistoryGUI();
    private StatisticalGUI Status = new StatisticalGUI();
    public static int employeeID = 100001;
    
    int width = 245;
    int height = 1140;
    
    
    
    //phương thức mở menu
    private void openMenuBar() {
                this.requestFocus();
        //tạo luồng chạy song song với luồng chính
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < width; i+=5) {
                    pMenu.setSize(i, height);
                    try {
                        // mở từ từ
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }
    
    //phương thức đóng menu
    private void closeMenuBar() {
        //tạo luồng chạy song song với luồng chính
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = width; i > 0; i-=5) {
                    pMenu.setSize(i, height);
                    try {
                        // đóng từ từ
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    
    }




	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		 if (e.getSource().equals(Contract.buttonPay)) {
                     if (Contract.table.getSelectedRow() != -1){
                         String a = String.valueOf(Contract.table.getValueAt(Contract.table.getSelectedRow(), 0));
                     }
                     
                     
                     
			 pMenuMain.remove(2);
			 
		     pMenuMain.add(Payment,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1580, 740));
		     Panel_ButtonMenu.setVisible(true);
		        setVisible(false);
		        setVisible(true);
                        
		     
		 }
	}
	
	
	
}